#use_frameworks!

platform :ios, '8.0'

target 'NYLSRWebSocket_Example' do
  pod 'NYLSRWebSocket', :path => '../'
  pod 'AFNetworking', '3.1.0'
  pod 'SocketRocket', '~> 0.5.1'
  pod 'SVProgressHUD', '2.0.3'
  target 'NYLSRWebSocket_Tests' do
    inherit! :search_paths

    
  end
end
